### ISSUE TITLE
Add/Edit a Product

### ISSUE THREAD

**Issue by dguglielmi-git** [dguglielmi-git/innovandoliving#63]
## Description
We need to be able to Add a new product or edit existing ones.

## Acceptance Criteria
- **Product List Section** 💼 
  - [ ] **Add/Edit products**
    - [ ] Create Form page for Add/Edit
    - [ ] Create Form Structure 
    - [ ] Allow saving a product without the functionality of uploading pictures
    - [ ] Add support for AWS S3 File uploading from backend and frontend
    - [ ] Upload file from the frontend and save the changes
    - [ ] **Add Product** button: open the form to complete the data for a new Product
    - [ ] **Edit Product** button: open the same previous form but this time with all the data loaded to allow the user make some changes on the product.  

## Important Details
- **Notes**: [ ]
- **Considerations**: [ ]

## Attachments
**Product Add/Edit Form Mockup**
![Image](https://github.com/user-attachments/assets/117533a4-0e50-4d4d-bfa6-4b3857eeb54c)

**Figma source:**
https://www.figma.com/file/azVHTRldGCgKXMe6ExQiTe/Untitled?type=design&node-id=0-1&mode=design&t=tt1zl7cw0uPNpfGD-0
- Get the CSS from the Figma file by using the Figma plugin: Focus CSS.

## Tasks
- [x] [ ]

**Comment by dguglielmi-git** [comment]
Pending translations:

- components\ProductManagement\Products\index
- components\ProductManagement\AddEditProduct\AddEditProductDetails
- components\ProductManagement\AddEditProduct\AddEditProductPicture
- components\Common\PictureGallery
- components\Common\UploadFiles
- pages\productmanagement\addproduct
-
